##---------------------------------------------------------
## 
## Project #2: TinyFP Arithmetic
##
## April 5, 2018
##
## Jin-Soo Kim (jinsoo.kim@snu.ac.kr)
## Systems Software Laboratory
## Dept. of Computer Science and Engineering
## Seoul National University
##
##---------------------------------------------------------


all: 
	gcc -Og -o pa2-test pa2.c pa2-test.c
clean:
	rm -f a.out pa2-test
